### ISSUE TITLE
Error when train model.

### ISSUE THREAD

**Issue by LeoniusChen** [ShihuaHuang95/FaPN-full#4]
Hi, I follow your instructions to arrange the project. However, this error still occurs. Could you help me with this issue?

KeyError: "No object named 'build_resnet_fan_backbone' found in 'BACKBONE' registry!"

**Comment by ShihuaHuang95** [comment]
Did you put the [additional files](https://github.com/ShihuaHuang95/FaPN-full/tree/main/detectron2) into Detectron2?

**Comment by LeoniusChen** [comment]
I figure it out that I need to put the fan.py related files into python/site-package/detectron2/xxx, not the local folder.
I have got similar training results as the paper announced. Thank you.
